{% set version = '0.999-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-expm
  version: {{ version|replace("-", "_") }}

source:
  fn: expm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/expm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/expm/expm_{{ version }}.tar.gz
  sha256: 511bac5860cc5b3888bca626cdf23241b6118eabcc82d100935386039e516412

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix

test:
  commands:
    - $R -e "library('expm')"           # [not win]
    - "\"%R%\" -e \"library('expm')\""  # [win]

about:
  home: http://R-Forge.R-project.org/projects/expm/
  license: GPL (>= 2)
  summary: Computation of the matrix exponential, logarithm, sqrt, and related quantities.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
