{% set version = "0.999-3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-expm
  version: {{ version|replace("-", "_") }}

source:
  fn: expm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/expm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/expm/expm_{{ version }}.tar.gz
  sha256: 511bac5860cc5b3888bca626cdf23241b6118eabcc82d100935386039e516412

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-matrix

  run:
    - r-base
    - r-matrix

test:
  commands:
    - $R -e "library('expm')"  # [not win]
    - "\"%R%\" -e \"library('expm')\""  # [win]

about:
  home: http://R-Forge.R-project.org/projects/expm/
  license: GPL (>= 2)
  summary: Computation of the matrix exponential, logarithm, sqrt, and related quantities.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
