appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 2hBg9yzjuaxW8nOdxNRKbBOFlgCJZT4xpZlKGtOSs4WOe17egWPJsKjLuzHMDuTAXOMBxal0Ff38ont35cEEY0VucNO42vVG1wGDPSM3z7QG42Ap+VW5v/8Y7rGshbYaHIEyc31efX1QzLD0MfL7J2FmO1QGZ9E4oZxIL4elPQvLKeDM8Tj+cBw04/tg/5BawmAaFIc8be5B4NyCa/epOyS5/hVx8kVX3pdWklnm2uCJsEkT2spHRSGtq6QhTPQmkLqoHiemF7kKUNL3dPIb2/coFLSrsCucJAldNBj6F+r1FlIy+iLF38UhHX9QFpnmIV8t0fjWU0V4iqIt4ImacUiujYk044mPUlqX2+BAEJJwgWrrXhr43XpPaGRJjEO+mDIQHQTzA58ZQOVfbm3fNdgxVu2IbaO3tZ6gshkRuhWc4AnYqW4qxTl2GE+PwFOd1YLOLqpraMCYNrMd5nTY5KrNQwxj3L0zNc4KZRiK/FU79MlWb4BL4IoxwtDywPG46uRIIXLGD9lj30pZlZMcu4XdYWBv/7s5D2LHpgSkhJJcwjzseiY/QaRgifxRXmN5E1S8UF9eHWPjnnw+t5aa7tqLOFizl/LSZGWUdTiqZUa5ea0ODMO6QtK9KX5I9b1bnhqWZFrmAPSP7IDablwbI4nYWCKWgDF1VBs+JMC9Amg=}
