travis:
  secure:
    BINSTAR_TOKEN: aIsspFZcFXFyXkujlRw9PX85Tkgcn5FRKobSNfSRTjBfg00TETczGSBSNHBccAASFjlSIxmIt4AR8ueEje/cCaedFAR1R1/liv5EuI1p8d7dwhiu6yNc8Ltk/BiYWrG+wp18MBJ5bBpyh1duX1l8PBiks+VA+vehJVd9mnNWHBgQ8OQP/+ly/ylz6fU5GM5wnyP26o8pbwttOoSrwrM3KgrKq3ppe27GVAVnhsX+8U6G7Hhtm2b9V+N2/YsCQV9SWK+zewQYhLovDEUVBNT1N9WKp3MF1QqzfdD4yQmzEV7dSuNCMJWeihgob0uCnFb+YVkYfDUnqOWsIV6EgzoRCfmtTF6fdbueW0eXlV+dCC4xmSSoizH35bciwcZGtTO1kk4p9hZNdbdlTfiKMZreiJqq9H6uiPMNKsDYnPxt21GV+zeJeyj1Ng+inQTqbKCSwpzlDby/CV5tIdFjb7+1cWJIequoK92TFPFSSzmXBaQLPzLVHjVaLIAQD/lbg4RIQ8BKoUl0UcxIAb4s0NJ18t1OG1ckID25KXKuoPV+muGfjHKijNiudSateWlM3faYRnKxiw+auUWwOciC+yVKZ1K4Qnu5O96ABMrZU+oMT9EGw+bqfwSJY/A2hYZgpwe2gE/A9uB8l/gatxT1osmaxUoqGUJlDPDV/8ujniqo9Fw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
